services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      RIDESCOPE_DATABASE_PATH: /app/data/ride_fare_comparision.db
    volumes:
      - ride-fare-comparision-data:/app/data
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"

volumes:
  ride-fare-comparision-data:
