FROM python:3.13-slim

LABEL org.opencontainers.image.title="Ride Fare Comparision Frontend"

WORKDIR /app
COPY frontend ./frontend
EXPOSE 8501
CMD ["python", "-m", "http.server", "8501", "--directory", "frontend"]
